name: Cypress E2E tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore: ['docs/**']

jobs:
  cypress-run:
    if: github.repository == 'redwoodjs/redwood'
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node-version: ['14', '16']
      fail-fast: true
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} | Node ${{ matrix.node-version }} latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # For network flakiness. See https://github.com/vercel/next.js/pull/28264
      - name: Tune linux network
        run: sudo ethtool -K eth0 tx off rx off

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache yarn
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-1234-${{ hashFiles('yarn.lock') }} #change yarn-{randomString} to bust the cache
          restore-keys: |
            yarn-1234

      - name: Install dependencies
        run: yarn install --immutable

      - name: Determine if the PR only changed docs
        id: only_changed_docs
        uses: ./.github/actions/only_changed_docs

      - name: Create a temporary directory
        if: fromJSON(steps.only_changed_docs.outputs.only_changed_docs) == false
        id: createpath
        run: |
          project_path=$(mktemp -d -t redwood.XXXXXX)
          echo "::set-output name=project_path::$project_path"
          framework_path=$(pwd)
          echo "::set-output name=framework_path::$framework_path"

      - name: Create a RedwoodJS app
        if: fromJSON(steps.only_changed_docs.outputs.only_changed_docs) == false
        run: ./tasks/run-e2e ${{ steps.createpath.outputs.project_path }} --no-start
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: Init Git for RedwoodJS app directory
        if: fromJSON(steps.only_changed_docs.outputs.only_changed_docs) == false
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git init --initial-branch main && git add .
          git commit -a --message=init
        working-directory: ${{ steps.createpath.outputs.project_path }}

      - name: Start server in background
        if: fromJSON(steps.only_changed_docs.outputs.only_changed_docs) == false
        run: yarn rw dev --no-generate --fwd="--no-open" &
        working-directory: ${{ steps.createpath.outputs.project_path }}

      - name: Cypress run
        if: fromJSON(steps.only_changed_docs.outputs.only_changed_docs) == false
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RW_PATH:  "${{ steps.createpath.outputs.project_path }}"
        with:
          # we've already installed dependencies
          install: false
          env: true
          browser: chrome
          record: false
          wait-on: 'http://localhost:8910'
          working-directory: ./tasks/e2e
          spec: |
             cypress/integration/01-tutorial/*.spec.js
             cypress/integration/04-logger/*.spec.js


